### PR TITLE
move to regular 4D interpolation function since we take logarithm of …

### PR DESCRIPTION
**Pull request by srichers**
…values before entering the interpolation function. Previous use of the _custom function resulted in the logarithm being taken twice

### CODE REVIEW

**Comment by jaharris87** [comment]
I don't understand.

`LogInterpolateSingleVariable_4D_Custom` does not calculate any logarithms (it expects all values to be logged before going in).

**Comment by jaharris87** [comment]
Also, all of the "non-Custom" routines are soon to disappear.

**Comment by jaharris87** [comment]
Ah, nevermind --- the `clean_up` that is going on right now in weaklib introduces the change to `LogInterpolateSingleVariable_4D_Custom`.

If you're okay with it, I'd just leave it as `LogInterpolateSingleVariable_4D_Custom` for now.

**Comment by srichers** [comment]
Good to know. Yes, I will keep my current setup until `clean_up` goes to `master`, and `thornado/interface_flash_OrderV` is updated with the new stuff.

**Comment by jaharris87** [comment]
@srichers 
`master` and `interface_flash_OrderV` have both been updated.

**Pull request closed without merging**
