### PR TITLE
AMD capability

### PR DESCRIPTION
**Pull request by jaharris87**
Adds ability to compile/run thornado on AMD GPUs.

Also a significant amount of general clean up and updates to work with recent weaklib clean up.

### CODE REVIEW

**Comment by srichers** [comment]
Errors in a module I don't use, but prevents compiling:

`../..//Modules/Opacities/OpacityModule_TABLE.F90:14:34:                                                                                                                                                            14 |   USE wlInterpolationModule, ONLY: &                                                                  |                                  1                                                              Error: Symbol ‘loginterpolatesinglevariable_1d3d’ referenced at (1) not found in module ‘wlinterpolationmodule’                                                                                                 ../..//Modules/Opacities/OpacityModule_TABLE.F90:16:45:                                                                                                                                                            16 |     LogInterpolateSingleVariable_1D3D_Custom, &                                                       |                                             1                                                   Error: Symbol ‘loginterpolatesinglevariable_2d2d’ referenced at (1) not found in module ‘wlinterpolationmodule’                                                                                                 make: *** [Makefile:158: OpacityModule_TABLE.o] Error 1   `

**Comment by srichers** [comment]
Though I don't understand - it looks like the relevant lines were commented out in the diff I see in github. Lemme double check things.

**Comment by jaharris87** [comment]
try again

**Comment by srichers** [comment]
That one is gone! Now I have:

TimeSteppingModule_Flash.F90:14:6:                                                                                                                                                                                 14 |   USE UtilitiesModule, ONLY: &                                                                        |      1                                                                                          Fatal Error: Cannot open module file ‘utilitiesmodule.mod’ for reading at (1): No such file or directorycompilation terminated.                                                                                 make: *** [Makefile:158: TimeSteppingModule_Flash.o] Error 1

**Comment by jaharris87** [comment]
ok, I think it was just a missing dependency.
should be good now

**Comment by srichers** [comment]
works for me now!

**Pull request merged**
